


import javax.swing.*;
import java.awt.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class ScheduleCard extends JPanel {


    public ScheduleCard(String date, String description, String time, Icon weatherIcon) {
        setLayout(null);
        setOpaque(false); // Make the background transparent for custom styling
        setBackground(new Color(255, 255, 255, 50)); // Soft white transparency
        setBounds(0, 0, 400, 100); // Default size, adjust as needed
        setBorder(BorderFactory.createLineBorder(new Color(220, 220, 220), 1)); // Soft border

        // Left Section: Date
        lblDate = new JLabel(date);
        lblDate.setFont(new Font("Montserrat SemiBold", Font.BOLD, 24));
        lblDate.setForeground(new Color(120, 150, 255)); // Adjust to match your theme
        lblDate.setHorizontalAlignment(SwingConstants.CENTER);
        lblDate.setBounds(10, 10, 80, 80); // Adjust size and position
        add(lblDate);

        // Center Section: Description
        lblDescription = new JLabel("<html>" + description + "</html>");
        lblDescription.setFont(new Font("Montserrat", Font.PLAIN, 14));
        lblDescription.setForeground(new Color(120, 150, 255));
        lblDescription.setBounds(100, 10, 200, 80);
        add(lblDescription);

        // Right Section: Weather Icon and Time
        lblWeather = new JLabel(weatherIcon);
        lblWeather.setBounds(310, 15, 50, 50); // Weather icon position
        add(lblWeather);

        lblTime = new JLabel(time);
        lblTime.setFont(new Font("Montserrat", Font.PLAIN, 12));
        lblTime.setForeground(new Color(120, 150, 255));
        lblTime.setHorizontalAlignment(SwingConstants.RIGHT);
        lblTime.setBounds(310, 60, 80, 20); // Time position
        add(lblTime);
    }

    // Optional: Update content dynamically
    public void updateCard(String date, String description, String time, Icon weatherIcon) {
        lblDate.setText(date);
        lblDescription.setText("<html>" + description + "</html>");
        lblTime.setText(time);
        lblWeather.setIcon(weatherIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDate = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblWeather = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        lblDate.setText("DD MM");

        lblDescription.setText("Description Goes Here");

        lblWeather.setText("icoWeather");

        lblTime.setText("Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblWeather)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTime)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWeather)
                        .addGap(18, 18, 18)
                        .addComponent(lblTime))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDescription)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblWeather;
    // End of variables declaration//GEN-END:variables
}
